sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '10'
  - '12'
script: npm run validate
jobs:
  include:
    - stage: release
      node_js: '12'
      deploy:
        provider: script
        script: npm run test:update && npx codecov && npx semantic-release
        skip_cleanup: true
branches:
  only: master
