#!/usr/bin/env bash
# Install dependencies for a given version of Svelte
set -euxo pipefail

svelte_version="${1-}"
node_version=$(node --version | sed 's/^v\([0-9]*\).*/\1/')
env_dir="tests/envs/svelte$svelte_version"
env_dir_by_node="$env_dir/node$node_version"

if [[ -d $env_dir_by_node ]]; then
  env_dir="$env_dir_by_node"
fi

if [[ "$svelte_version" == "5" ]]; then
  rm -rf coverage node_modules
  npm install
  exit 0
fi

if [[ -z "$svelte_version" ]]; then
  echo "Invalid usage: missing Svelte version" >&2;
  exit 1
fi

if [[ ! -d "$env_dir" ]]; then
  echo "Error: package.json for Svelte $svelte_version, Node $node_version not found" 1>&2
  exit 2
fi

rm -rf coverage node_modules "$env_dir/node_modules"
pushd "$env_dir"
npm install --no-package-lock --engine-strict
npm ls "$env_dir" svelte
popd
mv "$env_dir/node_modules" .
