#!/usr/bin/env bash
# Install dependencies for a given version of Svelte
set -euxo pipefail

svelte_version="${1-}"
node_version=$(node --version | sed 's/^v\([0-9]*\).*/\1/')
env_dir="tests/envs/svelte$svelte_version"
env_dir_by_node="$env_dir/node$node_version"

if [[ -d $env_dir_by_node ]]; then
  env_dir="$env_dir_by_node"
fi

clean_node_modules () {
  find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +
}

reset_package_json () {
  if [[ -f package.json.original ]]; then
    mv -f package.json.original package.json
  fi
}

trap "reset_package_json" EXIT

if [[ "$svelte_version" == "5" ]]; then
  clean_node_modules
  pnpm install
  exit 0
fi

if [[ -z "$svelte_version" ]]; then
  echo "Invalid usage: missing Svelte version" >&2;
  exit 1
fi

if [[ ! -d "$env_dir" ]]; then
  echo "Error: package.json for Svelte $svelte_version, Node $node_version not found" 1>&2
  exit 2
fi

clean_node_modules
mv package.json package.json.original
cp "$env_dir/package.json" package.json
pnpm install --no-lockfile
reset_package_json
